FROM ubuntu

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y git pkg-config wget libgtk2.0-dev pkg-config build-essential cmake libcanberra-gtk-module libcanberra-gtk3-module libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev 

RUN apt-get install -y python-pip mosquitto-clients
RUN pip install paho-mqtt

WORKDIR /
COPY message_fwd.py /
CMD python message_fwd.py
